# R
library(rCUR)
library(scatterplot3d)

p.vox=5803
p.sub=102
p.Af="../102subjectsXvox.4dfp.img"

Av=double(p.vox*p.sub)
Av=readBin(p.Af,double(),p.vox*p.sub,4)

#A=matrix(Av,nrow=p.vox,ncol=p.sub,dimnames=list(NULL,c(rep('HRP',36),rep('HRN',131),rep('LRN',66))))
A=matrix(Av,nrow=p.vox,ncol=p.sub,dimnames=list(NULL,c(rep('HRP',36),rep('LRN',66))))

##p.n=0.05
##q.n=round(p.vox*p.n)
##res=CUR(A,r=q.n)
##plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
##top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
##top.A=A[top.idx,]
##PCA02=prcomp(top.A,scale=TRUE)
##PCA01=prcomp(A,scale=TRUE)
##PCAs=rbind(PCA01$rotation[,c(1,2)],PCA02$rotation[,c(1,2)])
##group=rownames(PCAs)
##pchs=ifelse(group=='HRP',16,0)
##pchs=ifelse(group=='HRN',17,pchs)
##pchs=ifelse(group=='LRN',18,pchs)
###PCAs=data.frame(PC1=PCAs[,1],PC2=PCAs[,2],lab=c(rep('all',p.sub),rep('selected',p.sub)),group,pchs)
##dev.new()
##print(xyplot(PC2~PC1|lab,data=PCAs,pch=pchs,cex=1.0,col='black',fill='black',key=list(space="bottom",
##    text=list(levels(PCAs$group)),points=TRUE,pch=c(16,17,18),fill='black',columns=3,just=1)))

#fprintf(op,"Av=double(p.row*p.col)\n");
#fprintf(op,"Av=readBin(p.ifile,double(),p.row*p.col)\n");
#fprintf(op,"A=matrix(Av,nrow=p.row,ncol=p.col,byrow=p.byrow)\n");
#fprintf(op,"PCA01=prcomp(A,retx=TRUE)\n");
#fprintf(op,"fp=file(p.ofile0,'wb')\n");
#fprintf(op,"writeBin(as.vector(PCA01$rotation),fp)\n");
#fprintf(op,"close(fp)\n");
#fprintf(op,"fp=file(p.ofile1,'wb')\n");
#fprintf(op,"writeBin(as.vector(PCA01$x),fp)\n");
#fprintf(op,"close(fp)\n");

PCA01=prcomp(A,retx=TRUE)
PCA01.rot=PCA01$rotation[,c(1,2)]
group=rownames(PCA01.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA01.rot[,1],PC2=PCA01.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))
#dev.new()
#PCAs=data.frame(PC1=PCA01$rotation[,1],PC2=PCA01$rotation[,2],group,pchs)
#print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

PCA01=prcomp(A,scale=TRUE)
PCA01.rot=PCA01$rotation[,c(1,2)]
group=rownames(PCA01.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA01.rot[,1],PC2=PCA01.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

doit=0
if(doit==1){

p.n=0.9
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.8
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.7
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.6
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.5
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.4
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))
 
}

p.n=0.3
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.3
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
#top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))


doit=0
if(doit==1){

p.n=0.2
q.n=round(p.vox*p.n)
#res=CUR(A,r=q.n)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
#top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
#top.A=A[top.idx,]
res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=1)
top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.1
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=2)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))
}

p.n=0.05
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=2)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.05
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=2)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#top.A=getR(res)
PCA02=prcomp(top.A)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))




#}

p.n=0.01
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=2)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#top.A=getR(res)
PCA02=prcomp(top.A,scale=TRUE)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))

p.n=0.01
q.n=round(p.vox*p.n)
res=CUR(A,r=q.n)
#res=CUR(A,c=p.sub,r=q.n,method="ortho.top.scores",alpha=2)
#dev.new()
#plotLeverage(res,C=FALSE,top.n=q.n,xlab='voxel',las=1,top.col='black',top.pch=16,ul.col='black',ul.lty=2,col='grey')
top.idx=topLeverage(res,C=FALSE,top.n=q.n,sort=FALSE)
top.A=A[top.idx,]
#top.A=getR(res)
PCA02=prcomp(top.A)
PCA02.rot=PCA02$rotation[,c(1,2)]
group=rownames(PCA02.rot)
pchs=ifelse(group=='HRP',16,0)
pchs=ifelse(group=='HRN',17,pchs)
pchs=ifelse(group=='LRN',18,pchs)
cols=ifelse(group=='HRP','blue',0)
cols=ifelse(group=='HRN','red',cols)
cols=ifelse(group=='LRN','green',cols)
dev.new()
PCAs=data.frame(PC1=PCA02.rot[,1],PC2=PCA02.rot[,2],group,pchs)
print(xyplot(PC2~PC1,data=PCAs,pch=pchs,col=cols))


#}
